// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parkingbackend.Models;

namespace parkingbackend.Migrations
{
    [DbContext(typeof(ParkingContext))]
    [Migration("20210320135200_V2")]
    partial class V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Parkingbackend.Models.Parking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ime");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int")
                        .HasColumnName("Kapacitet");

                    b.Property<int>("M")
                        .HasColumnType("int")
                        .HasColumnName("M");

                    b.Property<int>("N")
                        .HasColumnType("int")
                        .HasColumnName("N");

                    b.HasKey("ID");

                    b.ToTable("Parking");
                });

            modelBuilder.Entity("Parkingbackend.Models.Polje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Boja")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Boja");

                    b.Property<int>("Counter")
                        .HasColumnType("int")
                        .HasColumnName("Counter");

                    b.Property<string>("Imeprezime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Imeprezime");

                    b.Property<string>("Marka")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Marka");

                    b.Property<int?>("ParkingID")
                        .HasColumnType("int");

                    b.Property<int>("Statusp")
                        .HasColumnType("int")
                        .HasColumnName("Statusp");

                    b.Property<string>("Tablice")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Tablice");

                    b.Property<string>("Vreme")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Vreme");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("X");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasColumnName("Y");

                    b.HasKey("ID");

                    b.HasIndex("ParkingID");

                    b.ToTable("Polje");
                });

            modelBuilder.Entity("Parkingbackend.Models.Polje", b =>
                {
                    b.HasOne("Parkingbackend.Models.Parking", "Parking")
                        .WithMany("ParkingPolja")
                        .HasForeignKey("ParkingID");

                    b.Navigation("Parking");
                });

            modelBuilder.Entity("Parkingbackend.Models.Parking", b =>
                {
                    b.Navigation("ParkingPolja");
                });
#pragma warning restore 612, 618
        }
    }
}
